// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.5.1
// source: combat.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Combat_MsgID_MsgID int32

const (
	Combat_MsgID_Heartbeat Combat_MsgID_MsgID = 0
	Combat_MsgID_JoinRoom  Combat_MsgID_MsgID = 1
	Combat_MsgID_GetMap    Combat_MsgID_MsgID = 2
	Combat_MsgID_Rool      Combat_MsgID_MsgID = 3
)

// Enum value maps for Combat_MsgID_MsgID.
var (
	Combat_MsgID_MsgID_name = map[int32]string{
		0: "Heartbeat",
		1: "JoinRoom",
		2: "GetMap",
		3: "Rool",
	}
	Combat_MsgID_MsgID_value = map[string]int32{
		"Heartbeat": 0,
		"JoinRoom":  1,
		"GetMap":    2,
		"Rool":      3,
	}
)

func (x Combat_MsgID_MsgID) Enum() *Combat_MsgID_MsgID {
	p := new(Combat_MsgID_MsgID)
	*p = x
	return p
}

func (x Combat_MsgID_MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Combat_MsgID_MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[0].Descriptor()
}

func (Combat_MsgID_MsgID) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[0]
}

func (x Combat_MsgID_MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Combat_MsgID_MsgID.Descriptor instead.
func (Combat_MsgID_MsgID) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0, 0}
}

type Combat_MsgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Combat_MsgID) Reset() {
	*x = Combat_MsgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Combat_MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Combat_MsgID) ProtoMessage() {}

func (x *Combat_MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Combat_MsgID.ProtoReflect.Descriptor instead.
func (*Combat_MsgID) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

type JoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomID string `protobuf:"bytes,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRoom) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *JoinRoom) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type CombatMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32   `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Items  []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CombatMap) Reset() {
	*x = CombatMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatMap) ProtoMessage() {}

func (x *CombatMap) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatMap.ProtoReflect.Descriptor instead.
func (*CombatMap) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{2}
}

func (x *CombatMap) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CombatMap) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CombatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CombatMap *CombatMap `protobuf:"bytes,1,opt,name=combatMap,proto3" json:"combatMap,omitempty"`
	Rool      bool       `protobuf:"varint,2,opt,name=rool,proto3" json:"rool,omitempty"`
	Pos       int32      `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Uid       string     `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Start     bool       `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *CombatInfo) Reset() {
	*x = CombatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatInfo) ProtoMessage() {}

func (x *CombatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatInfo.ProtoReflect.Descriptor instead.
func (*CombatInfo) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{3}
}

func (x *CombatInfo) GetCombatMap() *CombatMap {
	if x != nil {
		return x.CombatMap
	}
	return nil
}

func (x *CombatInfo) GetRool() bool {
	if x != nil {
		return x.Rool
	}
	return false
}

func (x *CombatInfo) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *CombatInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CombatInfo) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`     //1 梯子 2蛇
	Target int32 `protobuf:"varint,2,opt,name=Target,proto3" json:"Target,omitempty"` //跳转到指定格子
	Pos    int32 `protobuf:"varint,3,opt,name=Pos,proto3" json:"Pos,omitempty"`       //所在位置·
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Item) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type RoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoolReq) Reset() {
	*x = RoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoolReq) ProtoMessage() {}

func (x *RoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoolReq.ProtoReflect.Descriptor instead.
func (*RoolReq) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{5}
}

type RoolRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos  int32  `protobuf:"varint,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rool bool   `protobuf:"varint,2,opt,name=rool,proto3" json:"rool,omitempty"`
	Uid  string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RoolRsp) Reset() {
	*x = RoolRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoolRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoolRsp) ProtoMessage() {}

func (x *RoolRsp) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoolRsp.ProtoReflect.Descriptor instead.
func (*RoolRsp) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{6}
}

func (x *RoolRsp) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *RoolRsp) GetRool() bool {
	if x != nil {
		return x.Rool
	}
	return false
}

func (x *RoolRsp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_combat_proto protoreflect.FileDescriptor

var file_combat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x4a, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x5f, 0x4d, 0x73, 0x67,
	0x49, 0x44, 0x22, 0x3a, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6c, 0x10, 0x03, 0x22, 0x34,
	0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x4d, 0x61,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x43, 0x6f,
	0x6d, 0x62, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x62,
	0x61, 0x74, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x62,
	0x61, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x22, 0x44, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x6f, 0x6f,
	0x6c, 0x52, 0x65, 0x71, 0x22, 0x41, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6c, 0x52, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x6f,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_combat_proto_rawDescOnce sync.Once
	file_combat_proto_rawDescData = file_combat_proto_rawDesc
)

func file_combat_proto_rawDescGZIP() []byte {
	file_combat_proto_rawDescOnce.Do(func() {
		file_combat_proto_rawDescData = protoimpl.X.CompressGZIP(file_combat_proto_rawDescData)
	})
	return file_combat_proto_rawDescData
}

var file_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_combat_proto_goTypes = []interface{}{
	(Combat_MsgID_MsgID)(0), // 0: pb.Combat_MsgID.MsgID
	(*Combat_MsgID)(nil),    // 1: pb.Combat_MsgID
	(*JoinRoom)(nil),        // 2: pb.JoinRoom
	(*CombatMap)(nil),       // 3: pb.CombatMap
	(*CombatInfo)(nil),      // 4: pb.CombatInfo
	(*Item)(nil),            // 5: pb.Item
	(*RoolReq)(nil),         // 6: pb.RoolReq
	(*RoolRsp)(nil),         // 7: pb.RoolRsp
}
var file_combat_proto_depIdxs = []int32{
	5, // 0: pb.CombatMap.items:type_name -> pb.Item
	3, // 1: pb.CombatInfo.combatMap:type_name -> pb.CombatMap
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_combat_proto_init() }
func file_combat_proto_init() {
	if File_combat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_combat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Combat_MsgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombatMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoolRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_combat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_combat_proto_goTypes,
		DependencyIndexes: file_combat_proto_depIdxs,
		EnumInfos:         file_combat_proto_enumTypes,
		MessageInfos:      file_combat_proto_msgTypes,
	}.Build()
	File_combat_proto = out.File
	file_combat_proto_rawDesc = nil
	file_combat_proto_goTypes = nil
	file_combat_proto_depIdxs = nil
}
